#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Ibuki Hara
# SPDX-License-Identifier: GPL-3.0-only


import sys

def main():
    lines = sys.stdin.readlines() #標準入力を全部読み込む

    for line in lines:
        print(line, end="")  #そのまま出力する（動作確認用）

if __name__ == '__main__': #実行ガード（安全装置）
    main()
