#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Ibuki Hara
# SPDX-License-Identifier: BSD-3-Clause


import sys
import argparse

def main():
    parser = argparse.ArgumentParser(description='Markdown List Converter')
    parser.add_argument('-n', '--number', action='store_true')
    parser.add_argument('-c', '--check', action='store_true')
    args = parser.parse_args()

    i = 1
    for line in sys.stdin:
        line = line.rstrip()
        if not line: 
            continue

        if args.number:
            print(f"{i}. {line}")
            i += 1
        elif args.check:
            print(f"- [ ] {line}")
        else:
            print(f"- {line}")


if __name__ == '__main__': #実行ガード（安全装置）
    main()
